import { Integration } from "./IntegrationCard";

// Map of integration IDs to their corresponding secret names for auto-detection
export const INTEGRATION_SECRET_MAP: Record<string, string[]> = {
  slack: ["SLACK_CLIENT_ID", "SLACK_CLIENT_SECRET"],
  discord: ["DISCORD_BOT_TOKEN"],
  gmail: ["GMAIL_API_KEY"],
  google_calendar: ["GOOGLE_CALENDAR_API_KEY"],
  google_drive: ["GOOGLE_DRIVE_API_KEY"],
  google_sheets: ["GOOGLE_SHEETS_API_KEY"],
  google_docs: ["GOOGLE_DOCS_API_KEY"],
  hubspot: ["HUBSPOT_API_KEY"],
  pipedrive: ["PIPEDRIVE_API_KEY"],
  salesforce: ["SALESFORCE_API_KEY"],
  mailchimp: ["MAILCHIMP_API_KEY"],
  activecampaign: ["ACTIVECAMPAIGN_API_KEY"],
  asana: ["ASANA_API_KEY"],
  clickup: ["CLICKUP_API_KEY"],
  monday: ["MONDAY_API_KEY"],
  trello: ["TRELLO_API_KEY"],
  jira: ["JIRA_API_KEY"],
  notion: ["NOTION_API_KEY"],
  airtable: ["AIRTABLE_API_KEY"],
  todoist: ["TODOIST_API_KEY"],
  telegram: ["TELEGRAM_BOT_TOKEN"],
  whatsapp: ["WHATSAPP_API_KEY"],
  openai: ["OPENAI_API_KEY"],
  youtube: ["YOUTUBE_API_KEY"],
  calendly: ["CALENDLY_API_KEY"],
  typeform: ["TYPEFORM_API_KEY"],
  jotform: ["JOTFORM_API_KEY"],
  webflow: ["WEBFLOW_API_KEY"],
  motion: ["MOTION_API_KEY"],
  tldv: ["TLDV_API_KEY"],
  leadconnector: ["LEADCONNECTOR_API_KEY"],
  heygen: ["HEYGEN_API_KEY"],
  elevenlabs: ["ELEVENLABS_API_KEY"],
  pinterest: ["PINTEREST_APP_ID", "PINTEREST_APP_SECRET"],
  tiktok: ["TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
  resend: ["RESEND_API_KEY"],
  stripe: ["STRIPE_SECRET_KEY"],
  geekbot: ["GEEKBOT_API_KEY"],
  replicate: ["REPLICATE_API_TOKEN"],
  n8n: [], // n8n is always connected - hardcoded server URL
  x_twitter: ["XAI_API_KEY"], // Use existing X API key
};

export const INTEGRATION_CATEGORIES = {
  project_management: {
    label: "Project Management",
    description: "Track tasks, projects, and team workflows",
  },
  communication: {
    label: "Communication",
    description: "Team messaging, notifications, and collaboration",
  },
  crm_sales: {
    label: "CRM & Sales",
    description: "Customer relationships and sales pipelines",
  },
  productivity: {
    label: "Productivity",
    description: "Notes, calendars, and task management",
  },
  forms_surveys: {
    label: "Forms & Surveys",
    description: "Collect data and feedback",
  },
  email_marketing: {
    label: "Email & Marketing",
    description: "Email campaigns and automation",
  },
  storage_sheets: {
    label: "Storage & Sheets",
    description: "Documents, spreadsheets, and file storage",
  },
  automation: {
    label: "Automation",
    description: "Workflow automation and scheduling",
  },
  ecommerce: {
    label: "E-commerce",
    description: "Online stores and product management",
  },
  ai: {
    label: "AI & Intelligence",
    description: "AI assistants and smart automation",
  },
  video: {
    label: "Video & Media",
    description: "Video content and media management",
  },
};

export const ALL_INTEGRATIONS: Integration[] = [
  // Project Management
  {
    id: "asana",
    name: "Asana",
    description: "Project management and task tracking for teams",
    icon: "📋",
    category: "project_management",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developers.asana.com/docs/personal-access-token",
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "All-in-one productivity platform",
    icon: "✨",
    category: "project_management",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://clickup.com/api",
  },
  {
    id: "monday",
    name: "monday.com",
    description: "Work OS for teams to run projects and workflows",
    icon: "📊",
    category: "project_management",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developer.monday.com/",
  },
  {
    id: "trello",
    name: "Trello",
    description: "Visual project management with boards and cards",
    icon: "📌",
    category: "project_management",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developer.atlassian.com/cloud/trello/",
  },
  {
    id: "jira",
    name: "Jira Software Cloud",
    description: "Issue tracking and agile project management",
    icon: "🔷",
    category: "project_management",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developer.atlassian.com/cloud/jira/",
  },

  // Communication
  {
    id: "slack",
    name: "Slack",
    description: "Team messaging and collaboration hub",
    icon: "💬",
    category: "communication",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://api.slack.com/",
  },
  {
    id: "discord",
    name: "Discord",
    description: "Community messaging and voice chat",
    icon: "🎮",
    category: "communication",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://discord.com/developers/docs",
  },
  {
    id: "whatsapp",
    name: "WhatsApp Notifications",
    description: "Send notifications via WhatsApp Business API",
    icon: "📱",
    category: "communication",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developers.facebook.com/docs/whatsapp/",
  },
  {
    id: "telegram",
    name: "Telegram",
    description: "Instant messaging and bot notifications",
    icon: "✈️",
    category: "communication",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://core.telegram.org/bots/api",
  },
  {
    id: "gmail",
    name: "Gmail",
    description: "Send and receive emails via Google",
    icon: "📧",
    category: "communication",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/gmail/api",
  },
  {
    id: "outlook",
    name: "Microsoft Outlook",
    description: "Microsoft email and calendar integration",
    icon: "📨",
    category: "communication",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://learn.microsoft.com/en-us/graph/",
  },

  // CRM & Sales
  {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM, marketing, and sales automation",
    icon: "🧡",
    category: "crm_sales",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developers.hubspot.com/",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "Sales pipeline and CRM management",
    icon: "🎯",
    category: "crm_sales",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developers.pipedrive.com/",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Enterprise CRM and sales platform",
    icon: "☁️",
    category: "crm_sales",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developer.salesforce.com/",
  },
  {
    id: "leadconnector",
    name: "LeadConnector",
    description: "All-in-one marketing and sales platform",
    icon: "🔗",
    category: "crm_sales",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://highlevel.stoplight.io/docs/",
  },
  {
    id: "facebook_leads",
    name: "Facebook Lead Ads",
    description: "Capture leads from Facebook advertising",
    icon: "📘",
    category: "crm_sales",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.facebook.com/docs/marketing-api/",
  },

  // Productivity
  {
    id: "notion",
    name: "Notion",
    description: "All-in-one workspace for notes and databases",
    icon: "📝",
    category: "productivity",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developers.notion.com/",
  },
  {
    id: "google_calendar",
    name: "Google Calendar",
    description: "Schedule meetings and manage events",
    icon: "📅",
    category: "productivity",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/calendar/api",
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Flexible database and spreadsheet hybrid",
    icon: "🗃️",
    category: "productivity",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://airtable.com/developers/web/api",
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Task management and to-do lists",
    icon: "✅",
    category: "productivity",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developer.todoist.com/",
  },
  {
    id: "google_tasks",
    name: "Google Tasks",
    description: "Simple task lists integrated with Google",
    icon: "☑️",
    category: "productivity",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/tasks",
  },
  {
    id: "microsoft_todo",
    name: "Microsoft To Do",
    description: "Task management for Microsoft 365",
    icon: "📋",
    category: "productivity",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://learn.microsoft.com/en-us/graph/",
  },

  // Forms & Surveys
  {
    id: "google_forms",
    name: "Google Forms",
    description: "Create surveys and collect responses",
    icon: "📝",
    category: "forms_surveys",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/forms/api",
  },
  {
    id: "typeform",
    name: "Typeform",
    description: "Beautiful, conversational forms and surveys",
    icon: "💬",
    category: "forms_surveys",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developer.typeform.com/",
  },
  {
    id: "jotform",
    name: "Jotform",
    description: "Online form builder with powerful features",
    icon: "📋",
    category: "forms_surveys",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://api.jotform.com/docs/",
  },

  // Email & Marketing
  {
    id: "mailchimp",
    name: "Mailchimp",
    description: "Email marketing and automation platform",
    icon: "🐵",
    category: "email_marketing",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://mailchimp.com/developer/",
  },
  {
    id: "activecampaign",
    name: "ActiveCampaign",
    description: "Email marketing and CRM automation",
    icon: "📧",
    category: "email_marketing",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developers.activecampaign.com/",
  },

  // Storage & Sheets
  {
    id: "google_drive",
    name: "Google Drive",
    description: "Cloud storage and file management",
    icon: "📁",
    category: "storage_sheets",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/drive/api",
  },
  {
    id: "google_sheets",
    name: "Google Sheets",
    description: "Spreadsheets in the cloud",
    icon: "📊",
    category: "storage_sheets",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/sheets/api",
  },
  {
    id: "google_docs",
    name: "Google Docs",
    description: "Collaborative document editing",
    icon: "📄",
    category: "storage_sheets",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/docs/api",
  },
  {
    id: "microsoft_excel",
    name: "Microsoft Excel",
    description: "Spreadsheets and data analysis",
    icon: "📗",
    category: "storage_sheets",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://learn.microsoft.com/en-us/graph/",
  },

  // Automation
  {
    id: "n8n",
    name: "n8n Omega Alpha",
    description: "AURAOMEGA autonomous workflow automation engine",
    icon: "🔄",
    category: "automation",
    connectionType: "webhook",
    isConnected: true, // Force connected - hardcoded server URL
    syncStatus: "success",
    lastSyncAt: new Date().toISOString(),
    docsUrl: "https://docs.n8n.io/",
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "Connect apps and automate workflows",
    icon: "⚡",
    category: "automation",
    connectionType: "webhook",
    isConnected: false,
    docsUrl: "https://zapier.com/developer",
  },
  {
    id: "calendly",
    name: "Calendly",
    description: "Scheduling automation and booking",
    icon: "📅",
    category: "automation",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developer.calendly.com/",
  },
  {
    id: "motion",
    name: "Motion",
    description: "AI-powered calendar and task scheduling",
    icon: "🤖",
    category: "automation",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://motion.com/developers",
  },
  {
    id: "tldv",
    name: "tl;dv",
    description: "AI meeting recorder and summarizer",
    icon: "🎥",
    category: "automation",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://tldv.io/",
  },

  // E-commerce
  {
    id: "shopify",
    name: "Shopify",
    description: "E-commerce platform for online stores",
    icon: "🛍️",
    category: "ecommerce",
    connectionType: "native",
    isConnected: true, // Pre-connected via Lovable Shopify integration
    syncStatus: "success",
    lastSyncAt: new Date().toISOString(),
    docsUrl: "https://shopify.dev/docs",
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "Visual web design and CMS platform",
    icon: "🌐",
    category: "ecommerce",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://developers.webflow.com/",
  },

  // AI
  {
    id: "openai",
    name: "ChatGPT (OpenAI)",
    description: "AI assistant and text generation",
    icon: "🤖",
    category: "ai",
    connectionType: "api_key",
    isConnected: false,
    docsUrl: "https://platform.openai.com/docs/",
  },

  // Video
  {
    id: "youtube",
    name: "YouTube",
    description: "Video hosting and streaming platform",
    icon: "🎬",
    category: "video",
    connectionType: "oauth",
    isConnected: false,
    docsUrl: "https://developers.google.com/youtube/",
  },
  
  // Social Media
  {
    id: "x_twitter",
    name: "X (Twitter)",
    description: "Social media platform for posts and engagement",
    icon: "𝕏",
    category: "communication",
    connectionType: "api_key",
    isConnected: true, // Connected via XAI_API_KEY
    syncStatus: "success",
    lastSyncAt: new Date().toISOString(),
    docsUrl: "https://developer.x.com/",
  },
];

export function getIntegrationsByCategory(integrations: Integration[]) {
  const grouped: Record<string, Integration[]> = {};

  for (const integration of integrations) {
    if (!grouped[integration.category]) {
      grouped[integration.category] = [];
    }
    grouped[integration.category].push(integration);
  }

  return grouped;
}
