// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function result(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List synced Shopify products in the Dominion Revenue OS catalog, optionally filtered by a title/handle search term.",
  inputSchema: {
    search: z.string().optional().describe("Optional text to match against product title or handle."),
    limit: z.number().int().optional().describe("Maximum products to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("shopify_products").select("id, title, handle, price, currency_code, product_type, inventory_quantity, status, variant_id").order("updated_at", { ascending: false }).limit(take);
    if (search) query = query.or(`title.ilike.%${search}%,handle.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return result(data ?? [], { products: data ?? [] });
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "List orders",
  description: "List recent Shopify orders with totals, financial status, and fulfillment status.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Maximum orders to return (default 20, max 100)."),
    financial_status: z2.string().optional().describe("Optional filter, e.g. 'paid' or 'pending'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, financial_status }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("shopify_orders").select(
      "id, order_number, customer_email, total_price, currency, financial_status, fulfillment_status, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (financial_status) query = query.eq("financial_status", financial_status);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return result(data ?? [], { orders: data ?? [] });
  }
});

// src/lib/mcp/tools/revenue-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var revenue_summary_default = defineTool3({
  name: "revenue_summary",
  title: "Revenue summary",
  description: "Summarize order revenue over a recent window: total revenue, order count, and average order value.",
  inputSchema: {
    days: z3.number().int().optional().describe("Look-back window in days (default 30, max 365).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const window = Math.min(Math.max(days ?? 30, 1), 365);
    const since = new Date(Date.now() - window * 864e5).toISOString();
    const { data, error } = await supabaseForUser(ctx).from("shopify_orders").select("total_price, currency, created_at").gte("created_at", since).limit(1e3);
    if (error) return failure(error.message);
    const orders = data ?? [];
    const total = orders.reduce((sum, o) => sum + (parseFloat(String(o.total_price)) || 0), 0);
    const summary = {
      window_days: window,
      order_count: orders.length,
      total_revenue: Number(total.toFixed(2)),
      average_order_value: orders.length ? Number((total / orders.length).toFixed(2)) : 0,
      currency: orders[0]?.currency ?? "USD"
    };
    return result(summary, summary);
  }
});

// src/lib/mcp/tools/list-abandoned-carts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_abandoned_carts_default = defineTool4({
  name: "list_abandoned_carts",
  title: "List abandoned carts",
  description: "List abandoned carts awaiting recovery, with cart totals and contact details.",
  inputSchema: {
    include_recovered: z4.boolean().optional().describe("Include already-recovered carts (default false)."),
    limit: z4.number().int().optional().describe("Maximum carts to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_recovered, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("abandoned_carts").select("id, customer_email, cart_total, abandoned_at, recovered, recovery_revenue").order("abandoned_at", { ascending: false }).limit(take);
    if (!include_recovered) query = query.eq("recovered", false);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return result(data ?? [], { carts: data ?? [] });
  }
});

// src/lib/mcp/tools/list-creatives.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_creatives_default = defineTool5({
  name: "list_creatives",
  title: "List ad creatives",
  description: "List ad creatives with performance metrics (ROAS, spend, revenue, status) to review what is winning or losing.",
  inputSchema: {
    status: z5.string().optional().describe("Optional status filter, e.g. 'published', 'live', or 'killed'."),
    limit: z5.number().int().optional().describe("Maximum creatives to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("creatives").select("id, name, platform, status, roas, spend, revenue, conversions, created_at").order("revenue", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return failure(error.message);
    return result(data ?? [], { creatives: data ?? [] });
  }
});

// src/lib/mcp/tools/log-decision.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var log_decision_default = defineTool6({
  name: "log_decision",
  title: "Log an AI decision",
  description: "Record a decision or action in the Dominion Revenue OS AI decision log for the signed-in operator.",
  inputSchema: {
    decision_type: z6.string().describe("Short category, e.g. 'pricing', 'ad_scaling', 'inventory'."),
    action_taken: z6.string().describe("What was decided or done."),
    reasoning: z6.string().optional().describe("Why this decision was made."),
    confidence: z6.number().optional().describe("Confidence between 0 and 1.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ decision_type, action_taken, reasoning, confidence }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const score = Math.min(Math.max(confidence ?? 1, 0), 1);
    const { data, error } = await supabaseForUser(ctx).from("ai_decision_log").insert({
      user_id: ctx.getUserId(),
      decision_type,
      action_taken,
      reasoning: reasoning ?? null,
      confidence: score,
      execution_status: "completed"
    }).select().single();
    if (error) return failure(error.message);
    return result(data, { decision: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "phpektarjfbgnuyqjnmj";
var mcp_default = defineMcp({
  name: "dominion-revenue-os",
  title: "Dominion Revenue OS",
  version: "0.1.0",
  instructions: "Tools for Dominion Revenue OS (Aura Lift Essentials). Read the product catalog, orders, revenue summaries, abandoned carts, and ad creative performance, and log operator decisions. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, list_orders_default, revenue_summary_default, list_abandoned_carts_default, list_creatives_default, log_decision_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
